[package]
name = "tokio-rustls"
version = "0.13.1"
authors = ["quininer kel <quininer@live.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/tokio-rs/tls"
homepage = "https://github.com/tokio-rs/tls"
documentation = "https://docs.rs/tokio-rustls"
readme = "README.md"
description = "Asynchronous TLS/SSL streams for Tokio using Rustls."
categories = ["asynchronous", "cryptography", "network-programming"]
edition = "2018"

[dependencies]
tokio = "0.2.0"
futures-core = "0.3.1"
rustls = "0.17"
webpki = { version = "0.21", optional = true }

bytes = { version = "0.5", optional = true }

[features]
default = ["client", "server"]
client = ["webpki"]
early-data = []
dangerous_configuration = ["rustls/dangerous_configuration"]
server = []
unstable = ["bytes"]

[dev-dependencies]
tokio = { version = "0.2.0", features = ["macros", "net", "io-util", "rt-core", "time"] }
futures-util = "0.3.1"
lazy_static = "1"
webpki-roots = "0.19"

[[test]]
name = "test"
required-features = ["client", "server"]

[[test]]
name = "badssl"
required-features = ["client"]
